### ISSUE TITLE
Official Support for Debian 12 Bookworm

### ISSUE THREAD

**Issue by theoriginalguy** [bitwarden/self-host#115]
I know the stable release doesn't officially launch until 6/10/23, and that the self hosted documentation doesn't specifically call out any OS versions, but I wanted to confirm that this is going to be supported on launch day.

**Comment by Greenderella** [comment]
Hi there,

Thank you for checking up on this. Please feel free to report back if you encounter any trouble whilst attempting to set a self-hosted Bitwarden server up on Debian 12; I would recommend that you contact us (https://bitwarden.com/help/) if you have any further questions or if you encounter any problems, so we'd assist you.

On a personal note, if you're looking for the most stable experience for a production environment, I would recommend that you wait before upgrading your operating system to the latest release.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.

Thank you again.
