### ISSUE TITLE
self-hosting can't find sql server when bitwarden/mssql is installed

### ISSUE THREAD

**Issue by mynameisORIG** [bitwarden/self-host#165]
Hey, when trying to self-host on version 2023.9.1, I get this issue:
```
fail: Bit.Admin.HostedServices.DatabaseMigrationHostedService[0]
bitwarden-admin          |       Database unavailable for migration.
bitwarden-admin          |       Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
```
I followed everything here: https://bitwarden.com/help/install-on-premise-linux/

What am I doing incorrectly?

**Comment by TroyBW** [comment]
Hi there,

Please contact Bitwarden support using our contact form, so we can continue troubleshooting: [https://bitwarden.com/contact/ 
](https://bitwarden.com/contact/)
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
