### ISSUE TITLE
2023.10.10 Web not updated

### ISSUE THREAD

**Issue by ChrisSlashNull** [bitwarden/self-host#170]
#167 says Core Version and Web Version are upgraded to 2023.10.0
However Web Installed stays at 2023.9.2

vault.MYDOMAIN.com/admin/home/getinstalledwebversion returns: "2023.9.2"

![image](https://github.com/bitwarden/self-host/assets/128401608/63583604-10e8-419f-99eb-1b6709191822)

**Comment by Neonwarden** [comment]
Hi there,

Can you try updating your instance via the steps listed in this Help Center article? https://bitwarden.com/help/updating-on-premise/

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ChrisSlashNull** [comment]
Sorry for bothering, was in a little hurry while writing.
Forgot to mention that I'm on unified install.
Maybe only unified has the issue.
I also set up a new instance on another server for testing with the same issue.
Image: bitwarden/self-host:2023.10.0-beta

**Comment by ChrisSlashNull** [comment]
Fixed in 2023.10.1
