### ISSUE TITLE
Nginx can't bind to privileged ports

### ISSUE THREAD

**Issue by cepresso** [bitwarden/self-host#184]
When using the environment variables to set the exposed ports:
```
- BW_PORT_HTTP=80
- BW_PORT_HTTPS=443
```
nginx doesn't start with the following error message:
```
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```
I'm using a macvlan network so port mapping doesn't work.
Maybe it's possible to grant nginx privileges to bind to lower ports.

**Comment by nexcode** [comment]
https://github.com/bitwarden/server/issues/3258

**Comment by TroyBW** [comment]
Hi there,

If you are using the Bitwarden Unified setup, which is in beta, we recommend using the Docker Compose file Bitwarden provides here: https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-compose 

If additional assistance is required, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

The issue here will be closed.

Thanks!
