### ISSUE TITLE
Notification Banner

### ISSUE THREAD

**Issue by Ki8ae** [bitwarden/self-host#203]
Hello, I was wondering if it was possible to create a banner in a self hosted Bitwarden, where an admin can input text in. Similar to what Mattermost has under their Announcement Banner option. https://docs.mattermost.com/manage/announcement-banner.html

Please see screenshot of an example. Thank you
![Bitwarden Banner](https://github.com/bitwarden/self-host/assets/140206556/6e974355-986f-4e5e-b708-18c62ec0eb55)

**Comment by jtodddd** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
