### ISSUE TITLE
Docker unified self-host 2024.2.0-beta doesn't start

### ISSUE THREAD

**Issue by shofutex** [bitwarden/self-host#212]
I tried to pull 2024.2.0-beta and bitwarden doesn't start. There are no updates to the logs since starting this container and I get an empty reply from server trying to connect.

Switching back to 2024.1.2 is the only resolution.

Without logs updating, is there something I can do to get more insight into why 2024.2.0 is crashing?

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, so this may be an environmental or dependency issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by shofutex** [comment]
I will check further, but it sure sounds related to: https://github.com/bitwarden/self-host/issues/210
