### ISSUE TITLE
Provide systemd init script

### ISSUE THREAD

**Issue by sincerelysaucy** [bitwarden/self-host#229]
Starting bitwarden at boot time can be awkward. Please provide a systemd init script to ensure that the "docker" daemon is started first, then bitwarden, and to help ensure that bitwarden is restarted without manual intervention if the system fails or is rebooted.

**Comment by BBGhub** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
