### ISSUE TITLE
Version not match

### ISSUE THREAD

**Issue by baek-sang** [bitwarden/self-host#266]
<img width="508" alt="bw" src="https://github.com/bitwarden/self-host/assets/69100154/54cf225b-0402-4c53-9e14-2c178c0d6a4c">
<img width="358" alt="bwbw" src="https://github.com/bitwarden/self-host/assets/69100154/e1b32c3d-6378-4ee3-bd2f-26bf7477c230">

**Comment by SergeantConfused** [comment]
Hi @baek-sang,

Thank you for reporting this. Could you please clear the cache and cookie files and try again, or possibly hard-refresh (CTRL+SHIFT+R) the browser to reload that webpage? I ask because I see version 2024.6.1 when I visit the Bitwarden Web App.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
