### ISSUE TITLE
Allow Use of Docker Secrets for Sensitive Settings

### ISSUE THREAD

**Issue by MindsGoneAgain** [bitwarden/self-host#270]
I'd like to request that functionality is added to the docker image that allows it to accept docker secrets for sensitive data, such as Database name/user/password and SSL cert/keys.

It's my understanding that docker settings are accessible should someone malicious manage to get access to the container/service, but that docker secrets contain an extra layer of protection and cannot be accessed. This seems particularly important when protecting access to all the sensitive information stored on BitWarden.

An example of this is already located in the official postgres image's [docker-entrypoint.sh](https://github.com/docker-library/postgres/blob/9bf5a6d620a90158d8192ee0dba05acc4464d002/docker-entrypoint.sh#L9).

It uses the `file_env()` method to read in variables that may be stored in files ([references that can be pointed to docker secrets](https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets)).

While the postgres image uses `_FILE` at the end of settings to indicate that it should be read from a file, I would suggest that `_SECRET` might be better, indicating that it would be best to use a secret to pass in those settings with sensitive information.

I wouldn't mind coding this myself, but I am only familiar with the basics of shell scripting and docker (still googling and learning), and I didn't want to wait to suggest this. Additionally, I wanted to make sure that this would be a good idea that would be welcomed.

Thank you!

**Comment by BBGhub** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
