### ISSUE TITLE
Confused by all the containers + how to deploy on AWS ECS

### ISSUE THREAD

**Issue by dga-nagra** [bitwarden/self-host#279]
Hi,

I found this [link](https://community.bitwarden.com/t/docker-compose-yml-for-self-hosted-install/36371/2) where a docker-compose.yml is provided. It mentions the [stub version](https://github.com/bitwarden/server/releases).

My questions are:
* Why are there so many containers ?
* Why is there a bitwarden/mssql image/can't we just use a regular mssql database?
* Where is everything stored ? I was expecting most of the information to be in the database, but from the documentation, everything is written to disk ?

I am trying to setup a password manager, we want to use AWS ECS for that, but storage on disk is not great for that.
The documentation explain precises steps to follow to do one setup, but I am not getting the information needed to adapt the setup for our use.

Thank you for your help in understanding all of these.

**Comment by cbbit** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
