### ISSUE TITLE
error code: 1005

### ISSUE THREAD

**Issue by MatzFan** [bitwarden/self-host#41]
I am trying to install a self-hosted `bitwarden-server` on my local machine (Ubuntu 20.4). I have `docker` and `docker-compose` installed. I have downloaded `bitwarden.sh` from this repo, made it executable and then run it. The output is as follows:-
```
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2022.6.2
Docker version 20.10.17, build 100c701
docker-compose version 1.25.0, build unknown

~/bitwarden/bwdata/scripts/run.sh: line 1: error: command not found
```
Upon investigation the contents of ~/bitwarden/bwdata/scripts/run.sh are:

`error code: 1005`

Please advise how I should proceed, thanks.

**Comment by MatzFan** [comment]
I ought to have said I ran `./bitwarden.sh install`

**Comment by mimartin12** [comment]
Hey @MatzFan,

Do you have `curl` installed on the machine? You can quickly check by running `curl --version` and it should have a version output.

**Comment by MatzFan** [comment]
`curl 7.68.0 (x86_64-pc-linux-gnu)`

**Comment by mimartin12** [comment]
If the contents of the `~/bitwarden/bwdata/scripts/run.sh` are simply "error code: 1005". Then there is an issue with the machine pulling the latest `run.sh`. 

Since this is a new installation, I would suggest removing the entire `bwdata` folder and trying `./bitwarden.sh install` once again.

If the `~/bitwarden/bwdata/scripts/run.sh` continues to be populated with "error code: 1005", you can try to visit the URL that the `bitwarden.sh` script uses [directly](https://github.com/bitwarden/self-host/blob/master/bitwarden.sh#L40-L41) to rule out a networking error on the machine.

**Comment by MatzFan** [comment]
Resolved! Odd, but running the command again having deleted `bwdata` worked. Many thanks.
