### ISSUE TITLE
Copied working Bitwarden VM on ESXi to another data store Now I cannot log on with my email

### ISSUE THREAD

**Issue by witzker** [bitwarden/self-host#90]
Hi,

I have successfully setup Bitwarden in an Alpine machine on my tiny ESXi server. Created account, imported passwords - setup Browser clients, All works fine!

Now I shut down this VM1 and copied it with VMware vCenter Converter Standalone Client to another datastore on the same ESXi server with a different name.

This was reported as successful I started The VM2 and called it with IP in the browser I can see the login screen BUT I cannot log in with email and master password which I used in the VM1 which is still working fine.

What have I done wrong?

Are there some commands to repair or update Bitwarden in the VM2 so that I con login there.

Pls. Advice

Many THX

**Comment by chrizzlibaer** [comment]
Hi @witzker
I guess, since youre calling the copied instance via ip, you're also calling it via http instead of https? 
When I call my bitwarden instance via http, I also cannot login since the login screen refuses to do so. 
I throws an error on the top right corner:

An error occurred. 
Cannot read properties of null (reading 'importKey')

The error is gone when I access the site via https. 

I am not a developer, but maybe this helps. 

Best wishes,
Chris.

**Comment by chrizzlibaer** [comment]
After changing things in the global override environmentals you need to rebuild.
Rebuilding also should stop beforehand and start afterwards automatically.

**Comment by witzker** [comment]
so I did 

./bitwarden.sh restart
./bitwarden.sh rebuild
./bitwarden.sh start
now I get
![image](https://user-images.githubusercontent.com/4120266/229888535-4d63f894-1cbd-423b-b1ae-70c83ed5ca73.png)

Pls. Help

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, please check your ./bwdata/logs directory for more details.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
